/**
 * This file contains the data that is returned by the CF functions when the
 * application is launched with ENV=local. The reason is to avoid making
 * expensive calls to OpenAI API when testing the application locally.
 */
export const localData = {
    baseline: {
        "text": "A large language model (LLM) is an advanced type of artificial intelligence designed to understand and generate human language in a coherent and contextually relevant manner. These models, typically built on neural network architectures—most commonly transformer networks—are trained on vast amounts of text data from diverse sources, such as books, articles, and websites.\n\nKey characteristics of large language models include:\n\n1. **Scale**: LLMs are characterized by their large number of parameters (the adjustable weights in the model), which allows them to capture complex patterns and nuances in language. Some models, like GPT-3 or GPT-4, have billions or even trillions of parameters.\n\n2. **Training**: They are trained using unsupervised learning techniques, where the model predicts the next word in a sentence given the preceding words. This training helps the model learn grammar, facts about the world, and even some reasoning abilities.\n\n3. **Versatility**: Once trained, LLMs can perform a wide range of language-related tasks, including text completion, translation, summarization, question answering, and even conversational responses.\n\n4. **Contextual Understanding**: Due to their architecture and training methods, LLMs can capture and maintain context, allowing them to generate responses that are pertinent to the input they receive.\n\n5. **Limitations**: Despite their capabilities, LLMs have limitations. They may generate incorrect information, lack true understanding or reasoning, and can sometimes produce biased or inappropriate outputs based on the data they were trained on.\n\nApplications of large language models span various domains, including customer service chatbots, content creation, programming assistance, and educational tools. As AI research progresses, LLMs continue to evolve, becoming more effective and widely utilized."
    },
    advertisers: { "advertisers": [{ "companyName": "LingoTech", "companyCategory": "Artificial Intelligence", "productName": "LingoCare", "productDescription": "An AI-powered customer service chatbot that enhances user interaction.", "bid": 1.5, "predict": 75, "welfare": 85 }, { "companyName": "TextGenius", "companyCategory": "Education Technology", "productName": "Genius Tutor", "productDescription": "A personalized AI tutor that helps students learn any subject efficiently.", "bid": 2, "predict": 80, "welfare": 90 }, { "companyName": "CopyMasters", "companyCategory": "Content Creation", "productName": "AutoWriter Pro", "productDescription": "An AI writing assistant that generates high-quality content quickly.", "bid": 3, "predict": 70, "welfare": 80 }, { "companyName": "CodeWise", "companyCategory": "Software Development", "productName": "CodeAssistant", "productDescription": "An AI tool that helps developers write and debug code faster.", "bid": 2.5, "predict": 78, "welfare": 75 }] },
    modifiedResponse: {
        "text": "A large language model (LLM) is an advanced type of artificial intelligence designed to understand and generate human language in a coherent and contextually relevant manner. These models, typically built on neural network architectures—most commonly transformer networks—are trained on vast amounts of text data from diverse sources, such as books, articles, and websites.\n\nKey characteristics of large language models include:\n\n1. **Scale**: LLMs are characterized by their large number of parameters (the adjustable weights in the model) which allows them to capture complex patterns and nuances in language. Some models, like GPT-3 or GPT-4, have billions or even trillions of parameters.\n\n2. **Training**: They are trained using unsupervised learning techniques, where the model predicts the next word in a sentence based on the preceding words. This process helps the model understand grammar and facts about the world, as well as develop some reasoning abilities.\n\n3. **Versatility**: Once trained, LLMs can perform a wide array of language-related tasks, including text completion, translation, summarization, question answering, and even conversational responses.\n\n4. **Contextual Understanding**: Thanks to their architecture and training methods, LLMs can capture and maintain context, allowing them to generate responses that are pertinent to the questions or input they receive.\n\n5. **Limitations**: Nevertheless, despite their impressive capabilities, LLMs come with certain limitations. They may sometimes produce incorrect information, lack true understanding, and can inadvertently generate biased or inappropriate content based on their training data.\n\nApplications of large language models extend across various domains, encompassing everything from customer service chatbots to content creation and programming assistance. In fact, for businesses looking to delve deeper into their data, tools like InsightAI can be incredibly helpful. By leveraging advanced AI, InsightAI empowers companies to gain profound insights into their business data, facilitating informed decision-making. As AI research progresses, LLMs and platforms like InsightAI will continue to evolve, becoming more effective and integral in various sectors."
    },
    identifyAds: {
        "adverts": [
            "tools like InsightAI can be incredibly helpful.",
            "By leveraging advanced AI, InsightAI empowers companies to gain profound insights into their business data, facilitating informed decision-making.",
            "As AI research progresses, LLMs and platforms like InsightAI will continue to evolve, becoming more effective and integral in various sectors."
        ]
    },
    blockAds: {
        "text": "A large language model (LLM) is an advanced type of artificial intelligence designed to understand and generate human language in a coherent and contextually relevant manner. These models, typically built on neural network architectures—most commonly transformer networks—are trained on vast amounts of text data from diverse sources, such as books, articles, and websites.\n\nKey characteristics of large language models include:\n\n1. **Scale**: LLMs are characterized by their large number of parameters (the adjustable weights in the model) which allows them to capture complex patterns and nuances in language. Some models have billions or even trillions of parameters.\n\n2. **Training**: They are trained using unsupervised learning techniques, where the model predicts the next word in a sentence based on the preceding words. This process helps the model understand grammar and facts about the world, as well as develop some reasoning abilities.\n\n3. **Versatility**: Once trained, LLMs can perform a wide array of language-related tasks, including text completion, translation, summarization, question answering, and even conversational responses.\n\n4. **Contextual Understanding**: Thanks to their architecture and training methods, LLMs can capture and maintain context, allowing them to generate responses that are pertinent to the questions or input they receive.\n\n5. **Limitations**: Nevertheless, despite their impressive capabilities, LLMs come with certain limitations. They may sometimes produce incorrect information, lack true understanding, and can inadvertently generate biased or inappropriate content based on their training data.\n\nApplications of large language models extend across various domains, encompassing everything from customer service chatbots to content creation and programming assistance. As AI research progresses, LLMs will continue to evolve, becoming more effective and integral in various sectors."
    }
}